# Generated by Django 5.1.5 on 2025-01-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher.', max_length=50)),
                ('website', models.URLField(help_text="The publishser's website")),
                ('email', models.EmailField(help_text="Publisher's Email ID", max_length=254)),
            ],
        ),
    ]
